// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: CollectionService.proto

package LifeUnderWater;

public final class CollectionServiceOuterClass {
  private CollectionServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface RecordPathPointOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.RecordPathPoint)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 latitude_e7 = 1;</code>
     */
    long getLatitudeE7();

    /**
     * <code>int64 longitude_e7 = 2;</code>
     */
    long getLongitudeE7();
  }
  /**
   * <pre>
   * One point from the robot path.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.RecordPathPoint}
   */
  public  static final class RecordPathPoint extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.RecordPathPoint)
      RecordPathPointOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RecordPathPoint.newBuilder() to construct.
    private RecordPathPoint(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RecordPathPoint() {
      latitudeE7_ = 0L;
      longitudeE7_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RecordPathPoint(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              latitudeE7_ = input.readInt64();
              break;
            }
            case 16: {

              longitudeE7_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RecordPathPoint_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RecordPathPoint_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.class, LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.Builder.class);
    }

    public static final int LATITUDE_E7_FIELD_NUMBER = 1;
    private long latitudeE7_;
    /**
     * <code>int64 latitude_e7 = 1;</code>
     */
    public long getLatitudeE7() {
      return latitudeE7_;
    }

    public static final int LONGITUDE_E7_FIELD_NUMBER = 2;
    private long longitudeE7_;
    /**
     * <code>int64 longitude_e7 = 2;</code>
     */
    public long getLongitudeE7() {
      return longitudeE7_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitudeE7_ != 0L) {
        output.writeInt64(1, latitudeE7_);
      }
      if (longitudeE7_ != 0L) {
        output.writeInt64(2, longitudeE7_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitudeE7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, latitudeE7_);
      }
      if (longitudeE7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longitudeE7_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint)) {
        return super.equals(obj);
      }
      LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint other = (LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint) obj;

      boolean result = true;
      result = result && (getLatitudeE7()
          == other.getLatitudeE7());
      result = result && (getLongitudeE7()
          == other.getLongitudeE7());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_E7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLatitudeE7());
      hash = (37 * hash) + LONGITUDE_E7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongitudeE7());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * One point from the robot path.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.RecordPathPoint}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.RecordPathPoint)
        LifeUnderWater.CollectionServiceOuterClass.RecordPathPointOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RecordPathPoint_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RecordPathPoint_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.class, LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.Builder.class);
      }

      // Construct using LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitudeE7_ = 0L;

        longitudeE7_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RecordPathPoint_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint getDefaultInstanceForType() {
        return LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint build() {
        LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint buildPartial() {
        LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint result = new LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint(this);
        result.latitudeE7_ = latitudeE7_;
        result.longitudeE7_ = longitudeE7_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint) {
          return mergeFrom((LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint other) {
        if (other == LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint.getDefaultInstance()) return this;
        if (other.getLatitudeE7() != 0L) {
          setLatitudeE7(other.getLatitudeE7());
        }
        if (other.getLongitudeE7() != 0L) {
          setLongitudeE7(other.getLongitudeE7());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long latitudeE7_ ;
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public long getLatitudeE7() {
        return latitudeE7_;
      }
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public Builder setLatitudeE7(long value) {
        
        latitudeE7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public Builder clearLatitudeE7() {
        
        latitudeE7_ = 0L;
        onChanged();
        return this;
      }

      private long longitudeE7_ ;
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public long getLongitudeE7() {
        return longitudeE7_;
      }
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public Builder setLongitudeE7(long value) {
        
        longitudeE7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public Builder clearLongitudeE7() {
        
        longitudeE7_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.RecordPathPoint)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.RecordPathPoint)
    private static final LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint();
    }

    public static LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RecordPathPoint>
        PARSER = new com.google.protobuf.AbstractParser<RecordPathPoint>() {
      @java.lang.Override
      public RecordPathPoint parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RecordPathPoint(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RecordPathPoint> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RecordPathPoint> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.CollectionServiceOuterClass.RecordPathPoint getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CollectionSummaryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.CollectionSummary)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string result = 1;</code>
     */
    java.lang.String getResult();
    /**
     * <code>string result = 1;</code>
     */
    com.google.protobuf.ByteString
        getResultBytes();
  }
  /**
   * <pre>
   * Final result after the server receives all path points.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.CollectionSummary}
   */
  public  static final class CollectionSummary extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.CollectionSummary)
      CollectionSummaryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use CollectionSummary.newBuilder() to construct.
    private CollectionSummary(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CollectionSummary() {
      result_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private CollectionSummary(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              result_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_CollectionSummary_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_CollectionSummary_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.class, LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.Builder.class);
    }

    public static final int RESULT_FIELD_NUMBER = 1;
    private volatile java.lang.Object result_;
    /**
     * <code>string result = 1;</code>
     */
    public java.lang.String getResult() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        result_ = s;
        return s;
      }
    }
    /**
     * <code>string result = 1;</code>
     */
    public com.google.protobuf.ByteString
        getResultBytes() {
      java.lang.Object ref = result_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        result_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getResultBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, result_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getResultBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, result_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.CollectionServiceOuterClass.CollectionSummary)) {
        return super.equals(obj);
      }
      LifeUnderWater.CollectionServiceOuterClass.CollectionSummary other = (LifeUnderWater.CollectionServiceOuterClass.CollectionSummary) obj;

      boolean result = true;
      result = result && getResult()
          .equals(other.getResult());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.CollectionServiceOuterClass.CollectionSummary prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Final result after the server receives all path points.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.CollectionSummary}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.CollectionSummary)
        LifeUnderWater.CollectionServiceOuterClass.CollectionSummaryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_CollectionSummary_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_CollectionSummary_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.class, LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.Builder.class);
      }

      // Construct using LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        result_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_CollectionSummary_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.CollectionSummary getDefaultInstanceForType() {
        return LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.CollectionSummary build() {
        LifeUnderWater.CollectionServiceOuterClass.CollectionSummary result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.CollectionSummary buildPartial() {
        LifeUnderWater.CollectionServiceOuterClass.CollectionSummary result = new LifeUnderWater.CollectionServiceOuterClass.CollectionSummary(this);
        result.result_ = result_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.CollectionServiceOuterClass.CollectionSummary) {
          return mergeFrom((LifeUnderWater.CollectionServiceOuterClass.CollectionSummary)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.CollectionServiceOuterClass.CollectionSummary other) {
        if (other == LifeUnderWater.CollectionServiceOuterClass.CollectionSummary.getDefaultInstance()) return this;
        if (!other.getResult().isEmpty()) {
          result_ = other.result_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.CollectionServiceOuterClass.CollectionSummary parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.CollectionServiceOuterClass.CollectionSummary) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object result_ = "";
      /**
       * <code>string result = 1;</code>
       */
      public java.lang.String getResult() {
        java.lang.Object ref = result_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          result_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       */
      public com.google.protobuf.ByteString
          getResultBytes() {
        java.lang.Object ref = result_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          result_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string result = 1;</code>
       */
      public Builder setResult(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        result_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       */
      public Builder clearResult() {
        
        result_ = getDefaultInstance().getResult();
        onChanged();
        return this;
      }
      /**
       * <code>string result = 1;</code>
       */
      public Builder setResultBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        result_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.CollectionSummary)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.CollectionSummary)
    private static final LifeUnderWater.CollectionServiceOuterClass.CollectionSummary DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.CollectionServiceOuterClass.CollectionSummary();
    }

    public static LifeUnderWater.CollectionServiceOuterClass.CollectionSummary getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CollectionSummary>
        PARSER = new com.google.protobuf.AbstractParser<CollectionSummary>() {
      @java.lang.Override
      public CollectionSummary parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new CollectionSummary(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CollectionSummary> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CollectionSummary> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.CollectionServiceOuterClass.CollectionSummary getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface RobotStatusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.RobotStatus)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 battery_percentage = 1;</code>
     */
    int getBatteryPercentage();
  }
  /**
   * <pre>
   * A simple robot status message for the battery level.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.RobotStatus}
   */
  public  static final class RobotStatus extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.RobotStatus)
      RobotStatusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RobotStatus.newBuilder() to construct.
    private RobotStatus(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RobotStatus() {
      batteryPercentage_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RobotStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              batteryPercentage_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RobotStatus_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RobotStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.CollectionServiceOuterClass.RobotStatus.class, LifeUnderWater.CollectionServiceOuterClass.RobotStatus.Builder.class);
    }

    public static final int BATTERY_PERCENTAGE_FIELD_NUMBER = 1;
    private int batteryPercentage_;
    /**
     * <code>int32 battery_percentage = 1;</code>
     */
    public int getBatteryPercentage() {
      return batteryPercentage_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (batteryPercentage_ != 0) {
        output.writeInt32(1, batteryPercentage_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (batteryPercentage_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, batteryPercentage_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.CollectionServiceOuterClass.RobotStatus)) {
        return super.equals(obj);
      }
      LifeUnderWater.CollectionServiceOuterClass.RobotStatus other = (LifeUnderWater.CollectionServiceOuterClass.RobotStatus) obj;

      boolean result = true;
      result = result && (getBatteryPercentage()
          == other.getBatteryPercentage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + BATTERY_PERCENTAGE_FIELD_NUMBER;
      hash = (53 * hash) + getBatteryPercentage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.CollectionServiceOuterClass.RobotStatus prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A simple robot status message for the battery level.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.RobotStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.RobotStatus)
        LifeUnderWater.CollectionServiceOuterClass.RobotStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RobotStatus_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RobotStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.CollectionServiceOuterClass.RobotStatus.class, LifeUnderWater.CollectionServiceOuterClass.RobotStatus.Builder.class);
      }

      // Construct using LifeUnderWater.CollectionServiceOuterClass.RobotStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        batteryPercentage_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_RobotStatus_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.RobotStatus getDefaultInstanceForType() {
        return LifeUnderWater.CollectionServiceOuterClass.RobotStatus.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.RobotStatus build() {
        LifeUnderWater.CollectionServiceOuterClass.RobotStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.RobotStatus buildPartial() {
        LifeUnderWater.CollectionServiceOuterClass.RobotStatus result = new LifeUnderWater.CollectionServiceOuterClass.RobotStatus(this);
        result.batteryPercentage_ = batteryPercentage_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.CollectionServiceOuterClass.RobotStatus) {
          return mergeFrom((LifeUnderWater.CollectionServiceOuterClass.RobotStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.CollectionServiceOuterClass.RobotStatus other) {
        if (other == LifeUnderWater.CollectionServiceOuterClass.RobotStatus.getDefaultInstance()) return this;
        if (other.getBatteryPercentage() != 0) {
          setBatteryPercentage(other.getBatteryPercentage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.CollectionServiceOuterClass.RobotStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.CollectionServiceOuterClass.RobotStatus) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int batteryPercentage_ ;
      /**
       * <code>int32 battery_percentage = 1;</code>
       */
      public int getBatteryPercentage() {
        return batteryPercentage_;
      }
      /**
       * <code>int32 battery_percentage = 1;</code>
       */
      public Builder setBatteryPercentage(int value) {
        
        batteryPercentage_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 battery_percentage = 1;</code>
       */
      public Builder clearBatteryPercentage() {
        
        batteryPercentage_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.RobotStatus)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.RobotStatus)
    private static final LifeUnderWater.CollectionServiceOuterClass.RobotStatus DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.CollectionServiceOuterClass.RobotStatus();
    }

    public static LifeUnderWater.CollectionServiceOuterClass.RobotStatus getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<RobotStatus>
        PARSER = new com.google.protobuf.AbstractParser<RobotStatus>() {
      @java.lang.Override
      public RobotStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RobotStatus(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RobotStatus> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RobotStatus> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.CollectionServiceOuterClass.RobotStatus getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CommandOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.Command)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string action = 1;</code>
     */
    java.lang.String getAction();
    /**
     * <code>string action = 1;</code>
     */
    com.google.protobuf.ByteString
        getActionBytes();
  }
  /**
   * <pre>
   * The server replies with a simple action command.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.Command}
   */
  public  static final class Command extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.Command)
      CommandOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Command.newBuilder() to construct.
    private Command(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Command() {
      action_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Command(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              action_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_Command_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_Command_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.CollectionServiceOuterClass.Command.class, LifeUnderWater.CollectionServiceOuterClass.Command.Builder.class);
    }

    public static final int ACTION_FIELD_NUMBER = 1;
    private volatile java.lang.Object action_;
    /**
     * <code>string action = 1;</code>
     */
    public java.lang.String getAction() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        action_ = s;
        return s;
      }
    }
    /**
     * <code>string action = 1;</code>
     */
    public com.google.protobuf.ByteString
        getActionBytes() {
      java.lang.Object ref = action_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        action_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getActionBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, action_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getActionBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, action_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.CollectionServiceOuterClass.Command)) {
        return super.equals(obj);
      }
      LifeUnderWater.CollectionServiceOuterClass.Command other = (LifeUnderWater.CollectionServiceOuterClass.Command) obj;

      boolean result = true;
      result = result && getAction()
          .equals(other.getAction());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ACTION_FIELD_NUMBER;
      hash = (53 * hash) + getAction().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.CollectionServiceOuterClass.Command parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.CollectionServiceOuterClass.Command prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The server replies with a simple action command.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.Command}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.Command)
        LifeUnderWater.CollectionServiceOuterClass.CommandOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_Command_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_Command_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.CollectionServiceOuterClass.Command.class, LifeUnderWater.CollectionServiceOuterClass.Command.Builder.class);
      }

      // Construct using LifeUnderWater.CollectionServiceOuterClass.Command.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        action_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.CollectionServiceOuterClass.internal_static_LifeUnderWater_Command_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.Command getDefaultInstanceForType() {
        return LifeUnderWater.CollectionServiceOuterClass.Command.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.Command build() {
        LifeUnderWater.CollectionServiceOuterClass.Command result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.CollectionServiceOuterClass.Command buildPartial() {
        LifeUnderWater.CollectionServiceOuterClass.Command result = new LifeUnderWater.CollectionServiceOuterClass.Command(this);
        result.action_ = action_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.CollectionServiceOuterClass.Command) {
          return mergeFrom((LifeUnderWater.CollectionServiceOuterClass.Command)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.CollectionServiceOuterClass.Command other) {
        if (other == LifeUnderWater.CollectionServiceOuterClass.Command.getDefaultInstance()) return this;
        if (!other.getAction().isEmpty()) {
          action_ = other.action_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.CollectionServiceOuterClass.Command parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.CollectionServiceOuterClass.Command) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object action_ = "";
      /**
       * <code>string action = 1;</code>
       */
      public java.lang.String getAction() {
        java.lang.Object ref = action_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          action_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       */
      public com.google.protobuf.ByteString
          getActionBytes() {
        java.lang.Object ref = action_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          action_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder setAction(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        action_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder clearAction() {
        
        action_ = getDefaultInstance().getAction();
        onChanged();
        return this;
      }
      /**
       * <code>string action = 1;</code>
       */
      public Builder setActionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        action_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.Command)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.Command)
    private static final LifeUnderWater.CollectionServiceOuterClass.Command DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.CollectionServiceOuterClass.Command();
    }

    public static LifeUnderWater.CollectionServiceOuterClass.Command getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Command>
        PARSER = new com.google.protobuf.AbstractParser<Command>() {
      @java.lang.Override
      public Command parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Command(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Command> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Command> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.CollectionServiceOuterClass.Command getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_RecordPathPoint_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_RecordPathPoint_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_CollectionSummary_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_CollectionSummary_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_RobotStatus_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_RobotStatus_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_Command_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_Command_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027CollectionService.proto\022\016LifeUnderWate" +
      "r\"<\n\017RecordPathPoint\022\023\n\013latitude_e7\030\001 \001(" +
      "\003\022\024\n\014longitude_e7\030\002 \001(\003\"#\n\021CollectionSum" +
      "mary\022\016\n\006result\030\001 \001(\t\")\n\013RobotStatus\022\032\n\022b" +
      "attery_percentage\030\001 \001(\005\"\031\n\007Command\022\016\n\006ac" +
      "tion\030\001 \001(\t2\306\001\n\021CollectionService\022\\\n\024Reco" +
      "rdCollectionPath\022\037.LifeUnderWater.Record" +
      "PathPoint\032!.LifeUnderWater.CollectionSum" +
      "mary(\001\022S\n\027StartTargetedCollection\022\033.Life" +
      "UnderWater.RobotStatus\032\027.LifeUnderWater." +
      "Command(\0010\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LifeUnderWater_RecordPathPoint_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LifeUnderWater_RecordPathPoint_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_RecordPathPoint_descriptor,
        new java.lang.String[] { "LatitudeE7", "LongitudeE7", });
    internal_static_LifeUnderWater_CollectionSummary_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LifeUnderWater_CollectionSummary_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_CollectionSummary_descriptor,
        new java.lang.String[] { "Result", });
    internal_static_LifeUnderWater_RobotStatus_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LifeUnderWater_RobotStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_RobotStatus_descriptor,
        new java.lang.String[] { "BatteryPercentage", });
    internal_static_LifeUnderWater_Command_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_LifeUnderWater_Command_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_Command_descriptor,
        new java.lang.String[] { "Action", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
