// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PollutionLevelService.proto

package LifeUnderWater;

public final class PollutionLevelServiceOuterClass {
  private PollutionLevelServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PollutionLevelAskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.PollutionLevelAsk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 pollutionLevel = 1;</code>
     */
    int getPollutionLevel();
  }
  /**
   * <pre>
   * The client sends a base value that the server can build on.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.PollutionLevelAsk}
   */
  public  static final class PollutionLevelAsk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.PollutionLevelAsk)
      PollutionLevelAskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PollutionLevelAsk.newBuilder() to construct.
    private PollutionLevelAsk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PollutionLevelAsk() {
      pollutionLevel_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PollutionLevelAsk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              pollutionLevel_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelAsk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelAsk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.class, LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.Builder.class);
    }

    public static final int POLLUTIONLEVEL_FIELD_NUMBER = 1;
    private int pollutionLevel_;
    /**
     * <code>int32 pollutionLevel = 1;</code>
     */
    public int getPollutionLevel() {
      return pollutionLevel_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (pollutionLevel_ != 0) {
        output.writeInt32(1, pollutionLevel_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (pollutionLevel_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, pollutionLevel_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk)) {
        return super.equals(obj);
      }
      LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk other = (LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk) obj;

      boolean result = true;
      result = result && (getPollutionLevel()
          == other.getPollutionLevel());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + POLLUTIONLEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getPollutionLevel();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The client sends a base value that the server can build on.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.PollutionLevelAsk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.PollutionLevelAsk)
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelAsk_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelAsk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.class, LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.Builder.class);
      }

      // Construct using LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        pollutionLevel_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelAsk_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk getDefaultInstanceForType() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk build() {
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk buildPartial() {
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk result = new LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk(this);
        result.pollutionLevel_ = pollutionLevel_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk) {
          return mergeFrom((LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk other) {
        if (other == LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk.getDefaultInstance()) return this;
        if (other.getPollutionLevel() != 0) {
          setPollutionLevel(other.getPollutionLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int pollutionLevel_ ;
      /**
       * <code>int32 pollutionLevel = 1;</code>
       */
      public int getPollutionLevel() {
        return pollutionLevel_;
      }
      /**
       * <code>int32 pollutionLevel = 1;</code>
       */
      public Builder setPollutionLevel(int value) {
        
        pollutionLevel_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 pollutionLevel = 1;</code>
       */
      public Builder clearPollutionLevel() {
        
        pollutionLevel_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.PollutionLevelAsk)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.PollutionLevelAsk)
    private static final LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk();
    }

    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PollutionLevelAsk>
        PARSER = new com.google.protobuf.AbstractParser<PollutionLevelAsk>() {
      @java.lang.Override
      public PollutionLevelAsk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PollutionLevelAsk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PollutionLevelAsk> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PollutionLevelAsk> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelAsk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PollutionLevelRetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.PollutionLevelRet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 level = 1;</code>
     */
    int getLevel();
  }
  /**
   * <pre>
   * Each streamed message contains one pollution level result.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.PollutionLevelRet}
   */
  public  static final class PollutionLevelRet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.PollutionLevelRet)
      PollutionLevelRetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PollutionLevelRet.newBuilder() to construct.
    private PollutionLevelRet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PollutionLevelRet() {
      level_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PollutionLevelRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              level_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelRet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.class, LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.Builder.class);
    }

    public static final int LEVEL_FIELD_NUMBER = 1;
    private int level_;
    /**
     * <code>int32 level = 1;</code>
     */
    public int getLevel() {
      return level_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (level_ != 0) {
        output.writeInt32(1, level_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (level_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, level_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet)) {
        return super.equals(obj);
      }
      LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet other = (LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet) obj;

      boolean result = true;
      result = result && (getLevel()
          == other.getLevel());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LEVEL_FIELD_NUMBER;
      hash = (53 * hash) + getLevel();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Each streamed message contains one pollution level result.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.PollutionLevelRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.PollutionLevelRet)
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelRet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.class, LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.Builder.class);
      }

      // Construct using LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        level_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.internal_static_LifeUnderWater_PollutionLevelRet_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet getDefaultInstanceForType() {
        return LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet build() {
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet buildPartial() {
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet result = new LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet(this);
        result.level_ = level_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet) {
          return mergeFrom((LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet other) {
        if (other == LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet.getDefaultInstance()) return this;
        if (other.getLevel() != 0) {
          setLevel(other.getLevel());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int level_ ;
      /**
       * <code>int32 level = 1;</code>
       */
      public int getLevel() {
        return level_;
      }
      /**
       * <code>int32 level = 1;</code>
       */
      public Builder setLevel(int value) {
        
        level_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 level = 1;</code>
       */
      public Builder clearLevel() {
        
        level_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.PollutionLevelRet)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.PollutionLevelRet)
    private static final LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet();
    }

    public static LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PollutionLevelRet>
        PARSER = new com.google.protobuf.AbstractParser<PollutionLevelRet>() {
      @java.lang.Override
      public PollutionLevelRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PollutionLevelRet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PollutionLevelRet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PollutionLevelRet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.PollutionLevelServiceOuterClass.PollutionLevelRet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_PollutionLevelAsk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_PollutionLevelAsk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_PollutionLevelRet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_PollutionLevelRet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033PollutionLevelService.proto\022\016LifeUnder" +
      "Water\"+\n\021PollutionLevelAsk\022\026\n\016pollutionL" +
      "evel\030\001 \001(\005\"\"\n\021PollutionLevelRet\022\r\n\005level" +
      "\030\001 \001(\0052t\n\025PollutionLevelService\022[\n\021GetPo" +
      "llutionLevel\022!.LifeUnderWater.PollutionL" +
      "evelAsk\032!.LifeUnderWater.PollutionLevelR" +
      "et0\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LifeUnderWater_PollutionLevelAsk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LifeUnderWater_PollutionLevelAsk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_PollutionLevelAsk_descriptor,
        new java.lang.String[] { "PollutionLevel", });
    internal_static_LifeUnderWater_PollutionLevelRet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LifeUnderWater_PollutionLevelRet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_PollutionLevelRet_descriptor,
        new java.lang.String[] { "Level", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
