// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: PositionServer.proto

package LifeUnderWater;

public final class PositionServer {
  private PositionServer() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionAskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.PositionAsk)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 latitude_e7 = 1;</code>
     */
    long getLatitudeE7();

    /**
     * <code>int64 longitude_e7 = 2;</code>
     */
    long getLongitudeE7();
  }
  /**
   * <pre>
   * The request uses E7 values to keep coordinates as integers.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.PositionAsk}
   */
  public  static final class PositionAsk extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.PositionAsk)
      PositionAskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionAsk.newBuilder() to construct.
    private PositionAsk(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionAsk() {
      latitudeE7_ = 0L;
      longitudeE7_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionAsk(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              latitudeE7_ = input.readInt64();
              break;
            }
            case 16: {

              longitudeE7_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionAsk_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionAsk_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.PositionServer.PositionAsk.class, LifeUnderWater.PositionServer.PositionAsk.Builder.class);
    }

    public static final int LATITUDE_E7_FIELD_NUMBER = 1;
    private long latitudeE7_;
    /**
     * <code>int64 latitude_e7 = 1;</code>
     */
    public long getLatitudeE7() {
      return latitudeE7_;
    }

    public static final int LONGITUDE_E7_FIELD_NUMBER = 2;
    private long longitudeE7_;
    /**
     * <code>int64 longitude_e7 = 2;</code>
     */
    public long getLongitudeE7() {
      return longitudeE7_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitudeE7_ != 0L) {
        output.writeInt64(1, latitudeE7_);
      }
      if (longitudeE7_ != 0L) {
        output.writeInt64(2, longitudeE7_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitudeE7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, latitudeE7_);
      }
      if (longitudeE7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longitudeE7_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.PositionServer.PositionAsk)) {
        return super.equals(obj);
      }
      LifeUnderWater.PositionServer.PositionAsk other = (LifeUnderWater.PositionServer.PositionAsk) obj;

      boolean result = true;
      result = result && (getLatitudeE7()
          == other.getLatitudeE7());
      result = result && (getLongitudeE7()
          == other.getLongitudeE7());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_E7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLatitudeE7());
      hash = (37 * hash) + LONGITUDE_E7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongitudeE7());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.PositionAsk parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.PositionServer.PositionAsk prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The request uses E7 values to keep coordinates as integers.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.PositionAsk}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.PositionAsk)
        LifeUnderWater.PositionServer.PositionAskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionAsk_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionAsk_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.PositionServer.PositionAsk.class, LifeUnderWater.PositionServer.PositionAsk.Builder.class);
      }

      // Construct using LifeUnderWater.PositionServer.PositionAsk.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitudeE7_ = 0L;

        longitudeE7_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionAsk_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.PositionAsk getDefaultInstanceForType() {
        return LifeUnderWater.PositionServer.PositionAsk.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.PositionAsk build() {
        LifeUnderWater.PositionServer.PositionAsk result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.PositionAsk buildPartial() {
        LifeUnderWater.PositionServer.PositionAsk result = new LifeUnderWater.PositionServer.PositionAsk(this);
        result.latitudeE7_ = latitudeE7_;
        result.longitudeE7_ = longitudeE7_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.PositionServer.PositionAsk) {
          return mergeFrom((LifeUnderWater.PositionServer.PositionAsk)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.PositionServer.PositionAsk other) {
        if (other == LifeUnderWater.PositionServer.PositionAsk.getDefaultInstance()) return this;
        if (other.getLatitudeE7() != 0L) {
          setLatitudeE7(other.getLatitudeE7());
        }
        if (other.getLongitudeE7() != 0L) {
          setLongitudeE7(other.getLongitudeE7());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.PositionServer.PositionAsk parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.PositionServer.PositionAsk) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long latitudeE7_ ;
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public long getLatitudeE7() {
        return latitudeE7_;
      }
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public Builder setLatitudeE7(long value) {
        
        latitudeE7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public Builder clearLatitudeE7() {
        
        latitudeE7_ = 0L;
        onChanged();
        return this;
      }

      private long longitudeE7_ ;
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public long getLongitudeE7() {
        return longitudeE7_;
      }
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public Builder setLongitudeE7(long value) {
        
        longitudeE7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public Builder clearLongitudeE7() {
        
        longitudeE7_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.PositionAsk)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.PositionAsk)
    private static final LifeUnderWater.PositionServer.PositionAsk DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.PositionServer.PositionAsk();
    }

    public static LifeUnderWater.PositionServer.PositionAsk getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionAsk>
        PARSER = new com.google.protobuf.AbstractParser<PositionAsk>() {
      @java.lang.Override
      public PositionAsk parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionAsk(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionAsk> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PositionAsk> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.PositionServer.PositionAsk getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PositionRetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.PositionRet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    java.util.List<LifeUnderWater.PositionServer.Coordinate> 
        getPositionsList();
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    LifeUnderWater.PositionServer.Coordinate getPositions(int index);
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    int getPositionsCount();
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    java.util.List<? extends LifeUnderWater.PositionServer.CoordinateOrBuilder> 
        getPositionsOrBuilderList();
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    LifeUnderWater.PositionServer.CoordinateOrBuilder getPositionsOrBuilder(
        int index);
  }
  /**
   * <pre>
   * The response can return more than one coordinate.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.PositionRet}
   */
  public  static final class PositionRet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.PositionRet)
      PositionRetOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PositionRet.newBuilder() to construct.
    private PositionRet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PositionRet() {
      positions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PositionRet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                positions_ = new java.util.ArrayList<LifeUnderWater.PositionServer.Coordinate>();
                mutable_bitField0_ |= 0x00000001;
              }
              positions_.add(
                  input.readMessage(LifeUnderWater.PositionServer.Coordinate.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          positions_ = java.util.Collections.unmodifiableList(positions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionRet_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionRet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.PositionServer.PositionRet.class, LifeUnderWater.PositionServer.PositionRet.Builder.class);
    }

    public static final int POSITIONS_FIELD_NUMBER = 1;
    private java.util.List<LifeUnderWater.PositionServer.Coordinate> positions_;
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    public java.util.List<LifeUnderWater.PositionServer.Coordinate> getPositionsList() {
      return positions_;
    }
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    public java.util.List<? extends LifeUnderWater.PositionServer.CoordinateOrBuilder> 
        getPositionsOrBuilderList() {
      return positions_;
    }
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    public int getPositionsCount() {
      return positions_.size();
    }
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    public LifeUnderWater.PositionServer.Coordinate getPositions(int index) {
      return positions_.get(index);
    }
    /**
     * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
     */
    public LifeUnderWater.PositionServer.CoordinateOrBuilder getPositionsOrBuilder(
        int index) {
      return positions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < positions_.size(); i++) {
        output.writeMessage(1, positions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < positions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, positions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.PositionServer.PositionRet)) {
        return super.equals(obj);
      }
      LifeUnderWater.PositionServer.PositionRet other = (LifeUnderWater.PositionServer.PositionRet) obj;

      boolean result = true;
      result = result && getPositionsList()
          .equals(other.getPositionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getPositionsCount() > 0) {
        hash = (37 * hash) + POSITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPositionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.PositionRet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.PositionServer.PositionRet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * The response can return more than one coordinate.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.PositionRet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.PositionRet)
        LifeUnderWater.PositionServer.PositionRetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionRet_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionRet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.PositionServer.PositionRet.class, LifeUnderWater.PositionServer.PositionRet.Builder.class);
      }

      // Construct using LifeUnderWater.PositionServer.PositionRet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPositionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (positionsBuilder_ == null) {
          positions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          positionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_PositionRet_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.PositionRet getDefaultInstanceForType() {
        return LifeUnderWater.PositionServer.PositionRet.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.PositionRet build() {
        LifeUnderWater.PositionServer.PositionRet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.PositionRet buildPartial() {
        LifeUnderWater.PositionServer.PositionRet result = new LifeUnderWater.PositionServer.PositionRet(this);
        int from_bitField0_ = bitField0_;
        if (positionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            positions_ = java.util.Collections.unmodifiableList(positions_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.positions_ = positions_;
        } else {
          result.positions_ = positionsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.PositionServer.PositionRet) {
          return mergeFrom((LifeUnderWater.PositionServer.PositionRet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.PositionServer.PositionRet other) {
        if (other == LifeUnderWater.PositionServer.PositionRet.getDefaultInstance()) return this;
        if (positionsBuilder_ == null) {
          if (!other.positions_.isEmpty()) {
            if (positions_.isEmpty()) {
              positions_ = other.positions_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePositionsIsMutable();
              positions_.addAll(other.positions_);
            }
            onChanged();
          }
        } else {
          if (!other.positions_.isEmpty()) {
            if (positionsBuilder_.isEmpty()) {
              positionsBuilder_.dispose();
              positionsBuilder_ = null;
              positions_ = other.positions_;
              bitField0_ = (bitField0_ & ~0x00000001);
              positionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPositionsFieldBuilder() : null;
            } else {
              positionsBuilder_.addAllMessages(other.positions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.PositionServer.PositionRet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.PositionServer.PositionRet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<LifeUnderWater.PositionServer.Coordinate> positions_ =
        java.util.Collections.emptyList();
      private void ensurePositionsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          positions_ = new java.util.ArrayList<LifeUnderWater.PositionServer.Coordinate>(positions_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          LifeUnderWater.PositionServer.Coordinate, LifeUnderWater.PositionServer.Coordinate.Builder, LifeUnderWater.PositionServer.CoordinateOrBuilder> positionsBuilder_;

      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public java.util.List<LifeUnderWater.PositionServer.Coordinate> getPositionsList() {
        if (positionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(positions_);
        } else {
          return positionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public int getPositionsCount() {
        if (positionsBuilder_ == null) {
          return positions_.size();
        } else {
          return positionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public LifeUnderWater.PositionServer.Coordinate getPositions(int index) {
        if (positionsBuilder_ == null) {
          return positions_.get(index);
        } else {
          return positionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder setPositions(
          int index, LifeUnderWater.PositionServer.Coordinate value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.set(index, value);
          onChanged();
        } else {
          positionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder setPositions(
          int index, LifeUnderWater.PositionServer.Coordinate.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder addPositions(LifeUnderWater.PositionServer.Coordinate value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.add(value);
          onChanged();
        } else {
          positionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder addPositions(
          int index, LifeUnderWater.PositionServer.Coordinate value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.add(index, value);
          onChanged();
        } else {
          positionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder addPositions(
          LifeUnderWater.PositionServer.Coordinate.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.add(builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder addPositions(
          int index, LifeUnderWater.PositionServer.Coordinate.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder addAllPositions(
          java.lang.Iterable<? extends LifeUnderWater.PositionServer.Coordinate> values) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, positions_);
          onChanged();
        } else {
          positionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder clearPositions() {
        if (positionsBuilder_ == null) {
          positions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          positionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public Builder removePositions(int index) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.remove(index);
          onChanged();
        } else {
          positionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public LifeUnderWater.PositionServer.Coordinate.Builder getPositionsBuilder(
          int index) {
        return getPositionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public LifeUnderWater.PositionServer.CoordinateOrBuilder getPositionsOrBuilder(
          int index) {
        if (positionsBuilder_ == null) {
          return positions_.get(index);  } else {
          return positionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public java.util.List<? extends LifeUnderWater.PositionServer.CoordinateOrBuilder> 
           getPositionsOrBuilderList() {
        if (positionsBuilder_ != null) {
          return positionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(positions_);
        }
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public LifeUnderWater.PositionServer.Coordinate.Builder addPositionsBuilder() {
        return getPositionsFieldBuilder().addBuilder(
            LifeUnderWater.PositionServer.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public LifeUnderWater.PositionServer.Coordinate.Builder addPositionsBuilder(
          int index) {
        return getPositionsFieldBuilder().addBuilder(
            index, LifeUnderWater.PositionServer.Coordinate.getDefaultInstance());
      }
      /**
       * <code>repeated .LifeUnderWater.Coordinate positions = 1;</code>
       */
      public java.util.List<LifeUnderWater.PositionServer.Coordinate.Builder> 
           getPositionsBuilderList() {
        return getPositionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          LifeUnderWater.PositionServer.Coordinate, LifeUnderWater.PositionServer.Coordinate.Builder, LifeUnderWater.PositionServer.CoordinateOrBuilder> 
          getPositionsFieldBuilder() {
        if (positionsBuilder_ == null) {
          positionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              LifeUnderWater.PositionServer.Coordinate, LifeUnderWater.PositionServer.Coordinate.Builder, LifeUnderWater.PositionServer.CoordinateOrBuilder>(
                  positions_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          positions_ = null;
        }
        return positionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.PositionRet)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.PositionRet)
    private static final LifeUnderWater.PositionServer.PositionRet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.PositionServer.PositionRet();
    }

    public static LifeUnderWater.PositionServer.PositionRet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PositionRet>
        PARSER = new com.google.protobuf.AbstractParser<PositionRet>() {
      @java.lang.Override
      public PositionRet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PositionRet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PositionRet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PositionRet> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.PositionServer.PositionRet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CoordinateOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LifeUnderWater.Coordinate)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 latitude_e7 = 1;</code>
     */
    long getLatitudeE7();

    /**
     * <code>int64 longitude_e7 = 2;</code>
     */
    long getLongitudeE7();
  }
  /**
   * <pre>
   * A coordinate is one latitude and one longitude pair.
   * </pre>
   *
   * Protobuf type {@code LifeUnderWater.Coordinate}
   */
  public  static final class Coordinate extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LifeUnderWater.Coordinate)
      CoordinateOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Coordinate.newBuilder() to construct.
    private Coordinate(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Coordinate() {
      latitudeE7_ = 0L;
      longitudeE7_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Coordinate(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              latitudeE7_ = input.readInt64();
              break;
            }
            case 16: {

              longitudeE7_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_Coordinate_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_Coordinate_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              LifeUnderWater.PositionServer.Coordinate.class, LifeUnderWater.PositionServer.Coordinate.Builder.class);
    }

    public static final int LATITUDE_E7_FIELD_NUMBER = 1;
    private long latitudeE7_;
    /**
     * <code>int64 latitude_e7 = 1;</code>
     */
    public long getLatitudeE7() {
      return latitudeE7_;
    }

    public static final int LONGITUDE_E7_FIELD_NUMBER = 2;
    private long longitudeE7_;
    /**
     * <code>int64 longitude_e7 = 2;</code>
     */
    public long getLongitudeE7() {
      return longitudeE7_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (latitudeE7_ != 0L) {
        output.writeInt64(1, latitudeE7_);
      }
      if (longitudeE7_ != 0L) {
        output.writeInt64(2, longitudeE7_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (latitudeE7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, latitudeE7_);
      }
      if (longitudeE7_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, longitudeE7_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof LifeUnderWater.PositionServer.Coordinate)) {
        return super.equals(obj);
      }
      LifeUnderWater.PositionServer.Coordinate other = (LifeUnderWater.PositionServer.Coordinate) obj;

      boolean result = true;
      result = result && (getLatitudeE7()
          == other.getLatitudeE7());
      result = result && (getLongitudeE7()
          == other.getLongitudeE7());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + LATITUDE_E7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLatitudeE7());
      hash = (37 * hash) + LONGITUDE_E7_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLongitudeE7());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static LifeUnderWater.PositionServer.Coordinate parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(LifeUnderWater.PositionServer.Coordinate prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A coordinate is one latitude and one longitude pair.
     * </pre>
     *
     * Protobuf type {@code LifeUnderWater.Coordinate}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LifeUnderWater.Coordinate)
        LifeUnderWater.PositionServer.CoordinateOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_Coordinate_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_Coordinate_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                LifeUnderWater.PositionServer.Coordinate.class, LifeUnderWater.PositionServer.Coordinate.Builder.class);
      }

      // Construct using LifeUnderWater.PositionServer.Coordinate.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        latitudeE7_ = 0L;

        longitudeE7_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LifeUnderWater.PositionServer.internal_static_LifeUnderWater_Coordinate_descriptor;
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.Coordinate getDefaultInstanceForType() {
        return LifeUnderWater.PositionServer.Coordinate.getDefaultInstance();
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.Coordinate build() {
        LifeUnderWater.PositionServer.Coordinate result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public LifeUnderWater.PositionServer.Coordinate buildPartial() {
        LifeUnderWater.PositionServer.Coordinate result = new LifeUnderWater.PositionServer.Coordinate(this);
        result.latitudeE7_ = latitudeE7_;
        result.longitudeE7_ = longitudeE7_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof LifeUnderWater.PositionServer.Coordinate) {
          return mergeFrom((LifeUnderWater.PositionServer.Coordinate)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(LifeUnderWater.PositionServer.Coordinate other) {
        if (other == LifeUnderWater.PositionServer.Coordinate.getDefaultInstance()) return this;
        if (other.getLatitudeE7() != 0L) {
          setLatitudeE7(other.getLatitudeE7());
        }
        if (other.getLongitudeE7() != 0L) {
          setLongitudeE7(other.getLongitudeE7());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        LifeUnderWater.PositionServer.Coordinate parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (LifeUnderWater.PositionServer.Coordinate) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long latitudeE7_ ;
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public long getLatitudeE7() {
        return latitudeE7_;
      }
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public Builder setLatitudeE7(long value) {
        
        latitudeE7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 latitude_e7 = 1;</code>
       */
      public Builder clearLatitudeE7() {
        
        latitudeE7_ = 0L;
        onChanged();
        return this;
      }

      private long longitudeE7_ ;
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public long getLongitudeE7() {
        return longitudeE7_;
      }
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public Builder setLongitudeE7(long value) {
        
        longitudeE7_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 longitude_e7 = 2;</code>
       */
      public Builder clearLongitudeE7() {
        
        longitudeE7_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:LifeUnderWater.Coordinate)
    }

    // @@protoc_insertion_point(class_scope:LifeUnderWater.Coordinate)
    private static final LifeUnderWater.PositionServer.Coordinate DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new LifeUnderWater.PositionServer.Coordinate();
    }

    public static LifeUnderWater.PositionServer.Coordinate getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Coordinate>
        PARSER = new com.google.protobuf.AbstractParser<Coordinate>() {
      @java.lang.Override
      public Coordinate parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Coordinate(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Coordinate> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Coordinate> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public LifeUnderWater.PositionServer.Coordinate getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_PositionAsk_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_PositionAsk_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_PositionRet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_PositionRet_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LifeUnderWater_Coordinate_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LifeUnderWater_Coordinate_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024PositionServer.proto\022\016LifeUnderWater\"8" +
      "\n\013PositionAsk\022\023\n\013latitude_e7\030\001 \001(\003\022\024\n\014lo" +
      "ngitude_e7\030\002 \001(\003\"<\n\013PositionRet\022-\n\tposit" +
      "ions\030\001 \003(\0132\032.LifeUnderWater.Coordinate\"7" +
      "\n\nCoordinate\022\023\n\013latitude_e7\030\001 \001(\003\022\024\n\014lon" +
      "gitude_e7\030\002 \001(\0032Z\n\017PositionService\022G\n\013Ge" +
      "tPosition\022\033.LifeUnderWater.PositionAsk\032\033" +
      ".LifeUnderWater.PositionRetb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_LifeUnderWater_PositionAsk_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_LifeUnderWater_PositionAsk_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_PositionAsk_descriptor,
        new java.lang.String[] { "LatitudeE7", "LongitudeE7", });
    internal_static_LifeUnderWater_PositionRet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LifeUnderWater_PositionRet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_PositionRet_descriptor,
        new java.lang.String[] { "Positions", });
    internal_static_LifeUnderWater_Coordinate_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_LifeUnderWater_Coordinate_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LifeUnderWater_Coordinate_descriptor,
        new java.lang.String[] { "LatitudeE7", "LongitudeE7", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
